#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

printf "\e[33;1m%s\e[0m\n" 'Formatting code'

flutter format .

printf "\e[33;1m%s\e[0m\n" 'Format successfully!'

printf "\e[33;1m%s\e[0m\n" 'Analizing flutter project'

flutter analyze

if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Error!!! Please fix and commit again! 🤔'
  exit 1
fi

printf "\e[33;1m%s\e[0m\n" 'Errors not found. Good job! 👍'
